### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by kwikik** [PKU-YuanGroup/MagicTime#15] opened 2024-04-13 14:05 UTC
i install everything correctly and when i want to run an inference , i get this error.
People on the net with the same error told me that it can be corrupted file so i download everything again ( multiple time and i keep getting this error)  here the full error message 

Traceback (most recent call last):
  File "/home/azureuser/localfiles/MagicTime/inference_magictime.py", line 249, in <module>
    main(args)
  File "/anaconda/envs/magictime/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/localfiles/MagicTime/inference_magictime.py", line 61, in main
    text_encoder = CLIPTextModel.from_pretrained(model_config.pretrained_model_path, subfolder="text_encoder").cuda()
  File "/anaconda/envs/magictime/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3284, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by SHYuanBest** [comment] 2024-04-14 02:23
Thank you for your interest. I have never encountered this error. Maybe you can confirm whether the version information of the package is consistent with ours, or try to reconfigure the environment.

**Comment by SHYuanBest** [comment] 2024-04-15 12:09
It seems that there is a problem with your torch or transformers library. You can try to reinstall the same version as ours.

**Comment by kwikik** [comment] 2024-04-15 13:05
> It seems that there is a problem with your torch or transformers library. You can try to reinstall the same version as ours.

I already check the environnement but i will reinstall it from scratch i come home from work thx for your reply

**Comment by lckj2009** [comment] 2024-04-17 02:53
My server is already running MagicTime normally, but there is no model called "safetendersorust.Safetensor" on my server. Please check when this model was installed during the installation process

**Comment by truedat101** [comment] 2024-05-04 00:25
Maybe a duplicate of #21 .  Sorry I posted a dup!  Try making sure git-lfs is installed.  Then **redo** your installation.  Easiest way is to do "git checkout ckpts" to restore order.  Note, issues with these scripts #23 .

**Closed** 2024-06-29 13:45 UTC
